title: WebConf Jekyll Demo
email: libwebservices@miamioh.edu
description: Demonstrate a few features of the Jekyll Static Site Generator
baseurl: ''
url: ''
theme: minima
plugins:
  - jekyll-feed
  - jekyll-twitter-plugin
